package jp.project2by2.musicplayer.ui.player
import androidx.compose.runtime.Composable
import java.util.Locale
@Composable actual fun playerString(key: String): String = (if (Locale.getDefault().language == "ja") japanese else english)[key] ?: key
private val english = mapOf(
    "info_no_file_selected" to "No file selected",
    "action_add_to_playlist" to "Add to playlist",
    "action_create" to "Create",
    "action_create_playlist" to "Create playlist",
    "action_delete" to "Delete",
    "action_details" to "Details",
    "action_edit" to "Edit",
    "action_edit_loop_point" to "Edit Loop Point",
    "action_play_in_next_track" to "Play in next track",
    "action_rename" to "Rename",
    "action_rename_playlist" to "Rename playlist",
    "action_share" to "Share",
    "app_logo" to "App Logo",
    "back" to "Back",
    "browse" to "Browse",
    "button_sample_demo_music" to "Browse Sample MIDIs",
    "cancel" to "Cancel",
    "duration_placeholder" to "--:--",
    "folder_demo_name" to "Sample MIDI musics",
    "info_no_matching_files" to "No matching files",
    "info_no_mid_files_found" to "No files",
    "info_no_playlists_found" to "No playlists yet",
    "playlist_name_hint" to "Playlist name",
    "playlists" to "Playlists",
    "save" to "Save",
    "search" to "Search",
    "settings" to "Settings",
    "settings_category_midi_synthesizer" to "MIDI Synthesizer",
    "settings_category_playback" to "Playback",
    "settings_effects_reverb_strength" to "Reverb strength",
    "settings_effects_toggle_title" to "Enable Reverb / Chorus effects",
    "settings_max_voices_title" to "Max Voices",
    "settings_playback_loop_toggle" to "Enable Loop",
    "settings_playback_shuffle_toggle" to "Enable Shuffle",
    "settings_soundfont_load_button" to "Load SoundFont (*.sf2 / *.dls)",
    "settings_soundfont_loaded" to "Loaded",
    "settings_soundfont_not_set" to "Not set",
    "settings_soundfont_recommended_button" to "Download Recommended SoundFont",
    "settings_soundfont_loading_title" to "Loading SoundFont",
    "settings_soundfont_title" to "SoundFont",
    "share_copy_file" to "Copy file",
    "share_export_file" to "Save a copy",
    "share_file_hint" to "Copy the file to paste into another app, or save a copy.",
    "summary_midi_file_missing" to "File is missing",
    "topbar_search_summary" to "Search by filename / track name / artist",
    "view_grid" to "Grid",
    "view_list" to "List"
)
private val japanese = mapOf(
    "info_no_file_selected" to "ファイルが選択されていません",
    "action_add_to_playlist" to "プレイリストに追加",
    "action_create" to "作成",
    "action_create_playlist" to "プレイリストを作成",
    "action_delete" to "削除",
    "action_details" to "ファイルの詳細",
    "action_edit" to "編集",
    "action_edit_loop_point" to "ループポイントの編集",
    "action_play_in_next_track" to "次に再生",
    "action_rename" to "名前の変更",
    "action_rename_playlist" to "プレイリストの名前を変更",
    "action_share" to "シェアする",
    "app_logo" to "アプリロゴ",
    "back" to "戻る",
    "browse" to "ブラウズ",
    "button_sample_demo_music" to "サンプルMIDI一覧を表示",
    "cancel" to "キャンセル",
    "duration_placeholder" to "--:--",
    "folder_demo_name" to "サンプルMIDI楽曲",
    "info_no_matching_files" to "一致するファイルが見つかりませんでした",
    "info_no_mid_files_found" to "ファイルがありません",
    "info_no_playlists_found" to "プレイリストがありません",
    "playlist_name_hint" to "プレイリスト名",
    "playlists" to "プレイリスト",
    "save" to "保存",
    "search" to "検索",
    "settings" to "設定",
    "settings_category_midi_synthesizer" to "MIDI演奏オプション",
    "settings_category_playback" to "再生オプション",
    "settings_effects_reverb_strength" to "リバーブ効果の量",
    "settings_effects_toggle_title" to "リバーブ・コーラス効果",
    "settings_max_voices_title" to "最大発音数",
    "settings_playback_loop_toggle" to "ループ再生",
    "settings_playback_shuffle_toggle" to "シャッフル再生",
    "settings_soundfont_load_button" to "サウンドフォントを読み込む (*.sf2 / *.dls)",
    "settings_soundfont_loaded" to "読込済",
    "settings_soundfont_not_set" to "未設定",
    "settings_soundfont_recommended_button" to "おすすめのサウンドフォントを選択",
    "settings_soundfont_loading_title" to "サウンドフォントの読み込み中です",
    "settings_soundfont_title" to "サウンドフォント",
    "share_copy_file" to "ファイルをコピー",
    "share_export_file" to "名前を付けて書き出し",
    "share_file_hint" to "ファイルをコピーして他のアプリに貼り付けるか、別の場所に書き出します。",
    "summary_midi_file_missing" to "ファイルがありません",
    "topbar_search_summary" to "ファイル名・曲名・アーティストで検索",
    "view_grid" to "グリッド",
    "view_list" to "リスト"
)
